### PR TITLE
Small features

### PR DESCRIPTION
**Pull request by Smi0001**
## Feature or Issue
Fix for potential security vulnerability in repository

### Description:
Executed **npm audit fix --force**

### Team/Individual responsible:
@Smi0001 

### Reviewer:
@svudya

### CODE REVIEW

**Comment by Smi0001** [comment]
Closing this PR to open a new PR with new fix

**Comment by Smi0001** [comment]
Closing this PR to open a new PR with new fix

**Comment by Smi0001** [comment]
Closing this PR to open a new PR with new fix

**Comment by svudya** [comment]
Closing pull request without merging because some other changes are required

**Comment by svudya** [comment]
Pull request closed

**Pull request merged**
